vich_uploader:
    db_driver: orm

    mappings:
        product_picture:
            uri_prefix: '%app.path.product_picture%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_picture%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
